version: '3'

networks:
  backend:
  
services:
  postgres:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - .:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u inncent -d stocks_products"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  
  nginx:
    image: nginx:latest

  backend:
    build: .
    ports:
      - "8088:8000"



