version: '3'

networks:
  backend:
    driver: bridge
  
services:
  postgres:
    image: postgres:alpine
    env_file:
      - db.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - backend
    ports:
      - "8088:80"

  backend:
    build: .
    env_file:
      - .env
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

    



