version: '3'

networks:
  backend:
  
services:
  postgres:
    image: postgres:alpine
    env_file:
      - db.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u inncent -d stocks_products"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - backend

  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8088:8000"
    networks:
      - backend
    restart: unless-stopped
    depends_on:
      - postgres

    



