
POST http://127.0.0.1:5000/api/user
Content-Type: application/json;

{
    "name": "user_2", 
    "password": "12345678"
}

###

GET http://127.0.0.1:5000/api/user/1

###

PATCH  http://127.0.0.1:5000/api/user/1
Content-Type: application/json;

{
    "name": "user_1_new", 
    "email": "user1@mail.ru"
}

###

DELETE http://127.0.0.1:5000/api/user/3


###

POST http://127.0.0.1:5000/api/adv
Content-Type: application/json;
Authorization: Basic user_1:12345678

{
    "title": "my first adv new", 
    "description": "Simple description for my first adv"
}

###

GET http://127.0.0.1:5000/api/adv

###

PATCH  http://127.0.0.1:5000/api/adv/2
Content-Type: application/json;

{
    "title": "first adv title changed", 
    "description": "Simple description changed"
}

###

DELETE http://127.0.0.1:5000/api/adv/2